sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start creating an image with dockerfile"
  - docker build -t cyh0214/docker-react-app -f Dockerfile .

script:
  - docker run -e CI=true cyh0214/docker-react-app

after_success:
  - echo "Test success  "